### ISSUE TITLE
Hashtagify API

### ISSUE THREAD

**Issue by fguerra-hfarm** [fguerra-hfarm/hashtaggers#6]
We need to generate the needed token, check if it works, study any possible error code and then start querying data to get some useful insights to analyze/study the output of the API service provided by [Hashtagify](https://hashtagify.me). 
The documentation on the matter can be found on this page: [API manual](https://hashtagify.me/manual/api)

Once we manage to develop this, we need to develop the next step of needed code to begin following the organization stated in the issue #2. 

Working branch: *api_hashtagify*

**Comment by fguerra-hfarm** [comment]
The working branch for the API is now merged with the **use_dataset** files, so it's ready for the commits of your working code @VeDiego!

**Comment by VeDiego** [comment]
@fguerra-hfarm I committed the token generation function (9c63ddc044d097c8db0f1d20cb7dfca5be923b10) and I tried to use the new APIs in the commit 99af9e4fc1b0e96b7b314f02a702863c634695e7. I made some simple calls to get stats about hashtags and read the json.
@hashtaggers now that it works we can implement it even more. Go check it out!

**Comment by fguerra-hfarm** [comment]
> @fguerra-hfarm I committed the token generation function ([9c63ddc](https://github.com/fguerra-hfarm/hashtaggers/commit/9c63ddc044d097c8db0f1d20cb7dfca5be923b10)) and I tried to use the new APIs in the commit [99af9e4](https://github.com/fguerra-hfarm/hashtaggers/commit/99af9e4fc1b0e96b7b314f02a702863c634695e7). I made some simple calls to get stats about hashtags and read the json.
> @hashtaggers now that it works we can implement it even more. Go check it out!

Great! I've already started trying some new stuff, tomorrow you will see my improvements!

**Comment by fguerra-hfarm** [comment]
> > @fguerra-hfarm I committed the token generation function ([9c63ddc](https://github.com/fguerra-hfarm/hashtaggers/commit/9c63ddc044d097c8db0f1d20cb7dfca5be923b10)) and I tried to use the new APIs in the commit [99af9e4](https://github.com/fguerra-hfarm/hashtaggers/commit/99af9e4fc1b0e96b7b314f02a702863c634695e7). I made some simple calls to get stats about hashtags and read the json.
> > @hashtaggers now that it works we can implement it even more. Go check it out!
> 
> Great! I've already started trying some new stuff, tomorrow you will see my improvements!

As you guys can see, I added the check and read functions that we will need for a performant development of the `api_hashtagify.py` module (commit b2532e7149195912afa975dac7675fdf23c78b07).

**Comment by LeoLevisse** [comment]
Guys I've made some progress by processing some insights in the final print and created an output of the `.json` data that is generated from the API calls. We need to improve of course the print of the insights and to clean it even more (commit references 74604ae5578f58e5195cdc493258113b83819dbb and 2bbc67838f413ffe6ed915b95d35edeb71f49852).

**Comment by giorgiovizzini** [comment]
Now the print is more verbose and better integrated but still not clear from some output formats of the API (commit reference 1feebb96908c611a022cd7db0c84b356f59e120c).

**Comment by nicolamrv** [comment]
Now we have a more advanced print with some tables of specific variables that we selected from the `.json` (commit reference 638b82381aeee9d361bda112222a310f05a28182). The road is still long but I think that the solution we thought today will work.

**Comment by nicolamrv** [comment]
I kept working and I think I fixed the problems we talked about today regarding the verbose print which is still a work in progress. It is better now though. As you guys can see I've implemented also a new `check_langcode` function (commit reference 1c36b6af94f4024be5823fc75169cf97dac7a75b)

**Comment by fguerra-hfarm** [comment]
I managed to print the most **correlated hashtags** to the one selected for the analysis, and I improved the overall code in the process of reading the query's output (commit references ec1d7dfa1b915d3f251644de6081c6edc84caad6 and f1726cc7abda813c4b2890e30864c1f366840ee4). 
Now we could try to print those and their correlation values in a table, exactly like the other variables. Could you try it too @giorgiovizzini or someone else that is available today just to advance in the project? Let's move on and discard the idea if we can't, let me know. In my opinion, we already have a great print to show!

**Comment by giorgiovizzini** [comment]
I think we should move on other things and discard the idea! Are you trying the `menu_select` function that we talked about @fguerra-hfarm? (commit reference bb27dee1212c11266987e2bfcbd8b03239fbe75b)

**Comment by fguerra-hfarm** [comment]
> I think we should move on other things and discard the idea! Are you trying the `menu_select` function that we talked about @fguerra-hfarm? (commit reference [bb27dee](https://github.com/fguerra-hfarm/hashtaggers/commit/bb27dee1212c11266987e2bfcbd8b03239fbe75b))

Yes, I implemented it at line 50 (commit f37fcd4d4a60e772915ed2dd047b3f4b6b94d081). At the moment @giorgiovizzini I'm trying to integrate the `api_token.py` module inside of `api_hashtagify.py` and use its functions. Later we can try to slim down the code by importing it directly.

**Comment by VeDiego** [comment]
Now it should be at its final steps since I completed the integration of the `api_token.py` module (23950a93a0fd927ad73f8a24c537f575b2f7e1a7). If you have any ideas to improve it, go for it.

**Comment by VeDiego** [comment]
Guys `api_hashtagify.py` is fully developed.
We are ready to move into further development so I merged thew branch _api_hashtagify_ with branch _dev_.
